name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build Binary
        run: |
          GOARCH=arm64 go build -o kics ./cmd/console/main.go
          GOARCH=amd64 go build -o kics-amd64 ./cmd/console/main.go

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}
          name: "Release v${{ github.run_number }}"
          body: |
            Automatic release of the KICS binary built for arm64.
          artifacts: "kics"
